swiftmailer:
    transport: '%env(SENDGRID_TRANSPORT)%'
    host: '%env(SENDGRID_HOST)%'
    port: '%env(SENDGRID_PORT)%'
    encryption: '%env(SENDGRID_ENCRYPTION)%'
    username: '%env(SENDGRID_USERNAME)%'
    password: '%env(SENDGRID_PASSWORD)%'
    #spool: { type: 'memory' }
    #url: '%env(MAILER_URL)%'