<?php
/**
 * Created by PhpStorm.
 * User: marti
 * Date: 24/04/2018
 * Time: 14:42
 */

namespace App\UI\Form\Type;

use App\UI\Form\Type\Interfaces\ImageTypeInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImageType extends AbstractType implements ImageTypeInterface
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('image', FileType::class, array (
                'required' => true
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}
